### ISSUE TITLE
How to create a new Event

### ISSUE THREAD

**Issue by janlueders** [nhn/toast-ui.vue-calendar#22]
Hello,
how it is possible to extract the start and enddate to create a new Schedule in the list?
i need to use my own creationpopup and yes i know how to customize but i couldn't figure this point out. 
thank in advance for Help

**Comment by janlueders** [comment]
i was blind... so many trees but i didn't found the forest

**Comment by janlueders** [comment]
add the event was not a problem but in that way if i want to try to edit it, it is not possible.
I used in the called function 'onBeforeUpdateSchedule' 
`this.$store.dispatch('newSchedule',pl);
e.guide.clearGuideElement();`

to add the event and clear the guide.

if i try to edit the Schedule, i got the Error Message that guid is not defined.

Thank all in advance for a hint to look through the trees

**Comment by jungeun-cho** [comment]
@janlueders 
Check [this](https://github.com/nhn/tui.calendar/issues/98) out.


'the Error Message that guid is not defined.' => I'll check.

**Comment by janlueders** [comment]
thank you!!

and i did it like you can see [here](https://github.com/janlueders/grms/blob/master/tmp.js)
I tried to use the js doc to handle this problem but i didn't found anything

**Comment by jungeun-cho** [comment]
@janlueders 
Your link is broken.
Can you check the link again?

<img width="1201" alt="스크린샷 2019-06-27 15 55 43" src="https://user-images.githubusercontent.com/43128697/60243912-3d560300-98f4-11e9-86a0-5f58409a8e0d.png">

**Comment by janlueders** [comment]
sorry was a private repro.

https://jsfiddle.net/3sdf5a8b/

here is my Vue JS code.

**Comment by jungeun-cho** [comment]
@janlueders 
hm...
Title data is required.
First, open the schedule pop-up modal, and get the title.

```js
'beforeCreateSchedule': function(e) {
  console.log('beforeCreateSchedule', e);
  
  /* step1. open custom edit popup */
  /* 
    You need to open the modal window first and enter the title information!
  */
  // ex...
 const title = prompt('Schedule', '@suvrity\'s birthday');

  var schedule = {
    id: +new Date(),
    title: title, // title!!!!!!!!
    isAllDay: true,
    start: e.start,
    end: e.end,
    category:  'allday'
   };
   
  /* step2. save schedule */
  cal.createSchedules([schedule]);
  
  /* step3. clear guide element */
  e.guide.clearGuideElement();
},
```


Can you do this once?

**Comment by entropicrune** [comment]
jungeun-cho,  the snippet you provided above does help: I'm able to create a schedule.   When I do so, the time part of the calendar disappears.  Is that part of clearGuideElement()?  What do I need to do to keep (or get back) the time grid?

`import Calendar from 'tui-calendar/dist/tui-calendar';
import 'tui-calendar/dist/tui-calendar.css';

var calendar = new Calendar('#calendar', {
  defaultView: 'week', // 'month',
  taskView: true,
  template: {
  calendars: [
    {
      id: '1',
      name: 'My Calendar',
      color: '#ffffff',
      bgColor: '#9e5fff',
      dragBgColor: '#9e5fff',
      borderColor: '#9e5fff'
    },
    {
      id: '2',
      name: 'Company',
      color: '#00a9ff',
      bgColor: '#00a9ff',
      dragBgColor: '#00a9ff',
      borderColor: '#00a9ff'
    },
    ],

  // =======================================================================
  // ???? Would rather use defaults if I could!  But they don't seem to work
  useCreationPopup: false,
  useDetailPopup: false,
}
}
);


// event handlers
calendar.on({
  'clickSchedule': function(e) {
      console.log('clickSchedule', e);
  },
  'beforeCreateSchedule': function(e) {
    console.log('beforeCreateSchedule', e);

    /* step1. open custom edit popup */
    /*
      You need to open the modal window first and enter the title information!
    */
    // ex...
   const title = prompt('Schedule', 'Party');

    var schedule = {
      id: +new Date(),
      calendarId: '1',
      title: title, // title!!!!!!!!
      isAllDay: false,
      start: e.start,
      end: e.end,
      category:  'time'
     };

    /* step2. save schedule */
    calendar.createSchedules([schedule]);

    /* step3. clear guide element */
    e.guide.clearGuideElement();
  },

  'beforeUpdateSchedule': function(e) {
      console.log('beforeUpdateSchedule', e);
      e.schedule.start = e.start;
      e.schedule.end = e.end;
      calendar.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
  },
  'beforeDeleteSchedule': function(e) {
      console.log('beforeDeleteSchedule', e);
      calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);
  }
});
`

**Comment by nmacchitella** [comment]
Hey all, this is probably an extremely silly question BUT I am struggling to understand how can I pass to the BE the info of a new event from the moment I click "save" on the pop-up. Basically I click pop-up, the pop-up disappears but then I don't know where do those events go. I can't seem to find a post happening?  Any help?

**Comment by nmacchitella** [comment]
Hey all, 

this is probably an extremely silly question BUT I am struggling to understand how can I pass to the BE the info of a new event from the moment I click "save" on the pop-up. Basically I click pop-up, the pop-up disappears but then I don't know where do those events go. I can't seem to find a post happening?  Any help?

Just for context, I am implementing the calendar on Django app.

CC @dongsik-yoo as I saw you contributing to similar issues. Sorry if it's the wrong place to ask these questions.

**Comment by adhrinae** [comment]
@nmacchitella you can use `beforeCreateSchedule` event in order to pass the data to the BE.

https://github.com/nhn/toast-ui.vue-calendar#event
