### ISSUE TITLE
how can i modify/delete items in create schedule modal?

### ISSUE THREAD

**Issue by charmjeh** [nhn/toast-ui.vue-calendar#26]
hello!  i have another question.
1. how can i modify or delete item in create schedule modal?
2. can i limit the number of schedule per day?
(스케줄을 하루에 각 항목당 n개만 추가 가능하도록 하고 싶습니다.)
3. how can i use calendar in event? i tried to add beforeCreateSchedule event and create schedule,
 but an error has occurred

`Error in event handler for "beforeCreateSchedule": "TypeError: calendar.createSchedules is not a function"`

below is my calenar.vue code ( or check this out plz [link](https://jsfiddle.net/eunhee_ju/6Lsvr1fc/) )

```
<template>
  <calendar
    style="height: 800px;"
    ref="tuiCalendar"
    ...
    @beforeCreateSchedule="onBeforeCreateSchedule"
  />
</template>
<script>
import "tui-calendar/dist/tui-calendar.css";
import { Calendar } from "@toast-ui/vue-calendar";

export default {
  name: "Calendar",
  components: {
    calendar: Calendar
  },
  data() {
    return { ... }
  },
  methods: {
    onBeforeCreateSchedule(event) {

      schedule = {
        id: +new Date(),
        title: e.title,
        isAllDay: e.isAllDay,
        start: e.start,
        end: e.end,
        category: "allday"
      };

      var calendar = this.$refs.tuiCalendar;
      calendar.createSchedules([schedule]); //There was an error here
    }
  }
};
</script>
```

thank you for your time

## Version 
1.1.0

## Test Environment
Chrome : version 75.0.3770.100 (64bit), 
Vue.js

**Comment by dongsik-yoo** [comment]
You have to use the `schedules` prop. And if you want to use methods, use `invoke`. This is the [doc](https://github.com/nhn/toast-ui.vue-calendar#method)

**Comment by dongsik-yoo** [comment]
The default popup has the functionalities with `edit` and `delete`.
![image](https://user-images.githubusercontent.com/26706716/60938260-4b514e00-a30e-11e9-8ba4-031af91cb574.png)

**Comment by dongsik-yoo** [comment]
There is no way to limit schedule count that you want. I think you can filter schedules with a limitation.

**Comment by charmjeh** [comment]
안녕하세요, 답변 주셔서 감사합니다.

1. 스케줄 개수를 제한하는 기능은 없군요 ㅠ 알겠습니다 ㅎㅎ

2. 제가 수정하고자 했던것은 스케줄 생성 모달에서 location, busy/free, allday등의 항목이 있는데 
이 항목들을 제거하고 싶었던 것이었어요! 사용자 정의 모달을 사용해서만 할 수 있는 작업인가요?

3. "Error in event handler for "beforeCreateSchedule": "TypeError: calendar.createSchedules is not a function" 에러에 관한 답변은 제가 아직 초보라서 이해하지 못헀습니다...ㅜㅜ 번거로우시겠지만 간단한 코드로 설명해주실 수 있을까요?

**Comment by dongsik-yoo** [comment]
2. Yes, you can make own your popups. Please set `useCreationPopup = false` and check [the related documentation](https://nhn.github.io/tui.calendar/latest/Options)
3. You can invoke functions by using `invoke(methodName)`
```js
this.$refs.tuiCalendar.invoke('createSchedules');
```

**Comment by charmjeh** [comment]
말씀 주신대로 아래의 코드를 작성하니 해결되었습니다. 감사합니다

  methods: {
    onBeforeCreateSchedule(e) {
      var title = e.title;
      var startTime = e.start;
      var endTime = e.end;
      var isAllDay = e.isAllDay;
      var schedule;

      schedule = [
        {
          id: +new Date(),
          title: title,
          isAllDay: isAllDay,
          start: startTime,
          end: endTime,
          category: "allday"
        }
      ];

      this.$refs.tuiCalendar.invoke("createSchedules", schedule);
    },
}
