### ISSUE TITLE
how can i modify popup items?

### ISSUE THREAD

**Issue by charmjeh** [nhn/toast-ui.vue-calendar#27]
hello, Thanks to toast-ui team, I'm making calendars relatively easy and looks nice
Thank you for your effort :D

1. can i noticed shedule count per day?
If i already have one event and try to add another one, i want to show an alert window and overwrite it. (schedule). Do you already have the feature to know the number of schedules? Can I get some reference to this work if possible?

2. modify create schedule popup
i wanted to delete some items in create schedule popup,
so change both useCreationPopup and useDetailPopup to false.

but i don't know how to use tui.calendar popup template.(popup open & item modify)
how can i use creation popup/detail popup?

[here is my recent code. (link)](https://jsfiddle.net/eunhee_ju/6Lsvr1fc/19/)
check it out please.

thank you for your time

***
for creation popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleCreationPopup.hbs#L28-L32

for detail popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleDetailPopup.hbs#L10-L17

Originally posted by @dongsik-yoo in #217 (comment)

**Comment by jungeun-cho** [comment]
@charmjeh 
Set `useCreationPopup` and `useDetailPopup` to false and show the element(e.g. pop-up modal) you created in the `beforeCreateSchedule` event.

#### References
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

#### Example
```js
onBeforeCreateSchedule(e) {
  const draggingDataInfo = {
    id: e.id,
    start: e.start,
    end: e.end,
  };

  /*
  Open the pop-up modal and pass the start and end dates.
  For example, in a pop-up modal, you can enter a title for a schedule.

  Then, when you click the submit button, call the api to create the schedule.
  this.$refs.tuiCalendar.invoke ("createSchedules", schedule);
  */

  /*
  If you don't want to have a guideline border(blue line box) exposed when you click or drag,
  please clear the guideline.
  e.guide.clearGuideElement();
  */
},
```

**Comment by charmjeh** [comment]
```
<template>
  <div>
    <!-- creation popup : list -->
    <div>
      <v-menu v-model="showMenu" :position-x="x" :position-y="y" absolute offset-y>
        <v-list>
          <v-list-tile v-for="(item, index) in select" :key="index" @click>
            <v-list-tile-title @click="onCreateSchedule(item.name)">{{ item.name }}</v-list-tile-title>
          </v-list-tile>
        </v-list>
      </v-menu>
    </div>
      ...
      <calendar
        style="height: 800px;"
        ref="tuiCalendar"
        :schedules="scheduleList"
        :useCreationPopup="useCreationPopup"
        @beforeCreateSchedule="onBeforeCreateSchedule"
        ...
      />
    </div>
  </div>
</template>

<script>
import "../lib/tui-calendar/dist/tui-calendar.css";
import { Calendar } from "@toast-ui/vue-calendar";

export default {
  name: "myCalendar",
  components: {
    calendar: Calendar
  },
  mounted() {
    this.init();
  },
  data() {
    return {
      dialog: false,
      select: this.$store.state.select,
      useCreationPopup: false,
      useDetailPopup: true,
      count: 1,
      schedule: null,
      showMenu: false,
      x: 0,
      y: 0
     ...
    };
  },
  methods: {
    ....
    onCreateSchedule(value) {
      // add title and create schedule
      this.schedule[0].title = value;
      this.$refs.tuiCalendar.invoke("createSchedules", this.schedule);
    },
    onBeforeCreateSchedule(e) {
      // open custom popup
      var guide = e.guide;
      var guideEl$ = guide.guideElement
        ? guide.guideElement
        : guide.guideElements[Object.keys(guide.guideElements)[0]];
      this.x = guideEl$.getBoundingClientRect().left;
      this.y = guideEl$.getBoundingClientRect().top;
      this.showMenu = true;

      // schedule info
      var startTime = e.start;
      var endTime = e.end;
      var isAllDay = e.isAllDay;
      var schedule;

      this.schedule = [
        {
          id: this.count++,
          isAllDay: isAllDay,
          start: startTime,
          end: endTime,
          category: "allday",
          color: "#009eff",
          bgColor: "#e9f6fb",
          borderColor: "#009eff"
        }
      ];
      guide.clearGuideElement();
    },
  }
};
</script>



```

**Comment by charmjeh** [comment]
i solved this problem with getBoundingClientRect() and vuetify v-menu component.
thank you for your help :)

**Comment by WisdomSky** [comment]
Is there a way to re-purpose the current pop-up? I mean, I would like to use the same popup that the default one is showing. I don't want to write my own pop-up (using e.g Bootstrap Modal).

I just want a way to use that same pop-up but we will provide the custom content. Is that possible in vue's context?


I know I can overwrite the contents after it has been showing, but that's too invasive and doesn't comply with Vue's principles.
