### ISSUE TITLE
how to add an icon to front of the schedule name

### ISSUE THREAD

**Issue by charmjeh** [nhn/toast-ui.vue-calendar#29]
## Version

1.1.0
## Test Environment

chrome, vue.js

```js
<template>
      <calendar
        style="height: 800px;"
        ref="tuiCalendar"
        :schedules="scheduleList"
        :template="template"
      ...
      />
</template>
<script>
  data() {
    return {
     ...
      template: {
        schedule: function(schedule) {
          return getGridCategoryTemplate(schedule.category, schedule);
        }
      },
</script>
..
methods: {
    getGridCategoryTemplate(category, schedule) {
      console.log("hello");
      var tpl;

      switch (category) {
        case "milestone":
          tpl =
            '<span class="calendar-font-icon ic-milestone-b"></span> <span style="background-color: ' +
            schedule.bgColor +
            '">icontestttttt' +
            schedule.title +
            "</span>";
          break;
        case "task":
          tpl = "#icontestttttt" + schedule.title;
          break;
        case "allday":
          tpl = getTimeTemplate(schedule, true);
          break;
      }

      return tpl;
    },
    getTimeTemplate(schedule, isAllDay) {
      var html = [];

      if (!isAllDay) {
        html.push(
          "<strong>" +
            moment(schedule.start.getTime()).format("HH:mm") +
            "</strong> "
        );
      }
      if (schedule.isPrivate) {
        html.push('<span class="calendar-font-icon ic-lock-b"></span>');
        html.push(" Private");
      } else {
        if (schedule.isReadOnly) {
          html.push('<span class="calendar-font-icon ic-readonly-b"></span>');
        } else if (schedule.recurrenceRule) {
          html.push('<span class="calendar-font-icon ic-repeat-b"></span>');
        } else if (schedule.attendees.length) {
          html.push('<span class="calendar-font-icon ic-user-b"></span>');
        } else if (schedule.location) {
          html.push('<span class="calendar-font-icon ic-location-b"></span>');
        }
        html.push("icontestttttt " + schedule.title);
      }

      return html.join("");
    },
}

```

## Expected Behavior
I want to add an icon to front of the schedule name like below

![image](https://user-images.githubusercontent.com/43127789/61273655-ff5a4980-a7e4-11e9-8bf5-766018877a4e.png)

i tried to getTimeTemplate method and schedule templates but nothing happend.
how can i do this?

thank you for your time

**Comment by jungeun-cho** [comment]
@charmjeh 
Did you import the css file that declared this class selector?

https://github.com/nhn/toast-ui.vue-calendar#load

**Comment by charmjeh** [comment]
yes.

below is my code
```
import "tui-calendar/dist/tui-calendar.css";
import { Calendar } from "@toast-ui/vue-calendar";
```

**Comment by dongsik-yoo** [comment]
@charmjeh That is a kind of template function which gives your html and css. So that you have to include your css files.

**Comment by dongsik-yoo** [comment]
@charmjeh I mean that css(ex> `ic-user-b`) is not part of TOAST UI Calendar. It belongs service code not this library code.

**Comment by charmjeh** [comment]
1. It seems that the getTimeTemplate and getGridCategoryTemplate methods are not executed, rather than icon-style problems. There is no change when I insert test string ...
Which methods and templates are used to put icons in front of the schedule?

2. We are using vuetify. I added the calendar to another project file today, but the line-height is not correct as shown below. How do I change the style?
![image](https://user-images.githubusercontent.com/43127789/61344087-fb810280-a88a-11e9-91c1-ab0618d299a8.png)

**Comment by dongsik-yoo** [comment]
@charmjeh Use other template functions `time`, `allday` not `schedule`
```js
template: {
            allday: function(schedule) {
                return getGridCategoryTemplate(schedule.category, schedule);
            },
            time: function(schedule) {
                return getGridCategoryTemplate(schedule.category, schedule);
            }
        }
```

**Comment by charmjeh** [comment]
1. it works! thank you
2. I tried to modify the line-height using .tui-full-calendar-weekday-schedule-title. 
it works with developer tools but modifying the style tag doesn't work as expected

**Comment by dongsik-yoo** [comment]
@charmjeh 
2. In that case, you can override that css selector. Another option is to use own your css selector.

**Comment by charmjeh** [comment]
i will try that! thank you
