### ISSUE TITLE
can i set background opacity?

### ISSUE THREAD

**Issue by charmjeh** [nhn/toast-ui.vue-calendar#30]
can i set background opacity?
I would like to have the following result with one color value:

![image](https://user-images.githubusercontent.com/43127789/61439979-7d515880-a97d-11e9-9b19-4f804f678eab.png)

**Comment by dongsik-yoo** [comment]
Sure. You can change background-color of a schedule. Check [Schedule.bgColor](https://nhn.github.io/tui.calendar/latest/Schedule) documentation.

**Comment by dongsik-yoo** [comment]
Another options is `Calendar.setCalendarColor`. See the documentation [here](https://nhn.github.io/tui.calendar/latest/Calendar#setCalendarColor).

**Comment by charmjeh** [comment]
I solved this problem by putting an rgba value in bgColor. thank you for your help :)

schedule.bgColor = "rgba(0,158,255,1)"
