### ISSUE TITLE
Weekly view: how to go to next/prev week?

### ISSUE THREAD

**Issue by mariusa** [nhn/toast-ui.vue-calendar#40]
Question: the demo here has nice buttons to switch weeks (Today, prev/next, see current week)
https://nhn.github.io/tui.calendar/latest/tutorial-example02-weekly

How can we get the same?

Thanks!

**Comment by dongsik-yoo** [comment]
@mariusa It's a example html page. You can find it [here](https://github.com/nhn/tui.calendar/blob/master/examples/example02-weekly.html).

**Comment by mariusa** [comment]
Thanks! It works!

I've read https://github.com/nhn/toast-ui.vue-calendar and made it work like this:

```
        <b-button @click="calendarPrev">Prev</b-button>
        <calendar
          ref="calendar"
          style="height: auto;"
          :taskView="false"
          :week="{startDayOfWeek: 1, hourStart: 8, hourEnd: 22}"
        />
...

  methods: {

    calendarPrev() {
      this.$refs.calendar.invoke('prev')
    },

```
