### ISSUE TITLE
캘린더 달(month) 이동

### ISSUE THREAD

**Issue by charmjeh** [nhn/toast-ui.vue-calendar#42]
## Version

    "tui-calendar": "^1.12.3",
    "tui-date-picker": "^4.0.0",

## Test Environment

크롬 77.0.3865.120（Official Build） （64비트）

## Code
```js
// Write example code
    init() {
      this.calendar = new Calendar(this.$refs.calendar, this.calendarOptions);
      /* ... */
    },
    /* ... */

    setCalendarMonth(val) {
      if (val === -1) {
        this.calendar.prev();
      } else if (val === 1) {
        this.calendar.next();
      } else if (val === 0) {
        this.calendar.today();
      }
      /* ... */
      this.calendarYear = this.calendar.getDate().getFullYear();
      this.calendarMonth = this.calendar.getDate().getMonth() + 1;
      /* ... */
   }
```

## Expected Behavior

안녕하세요! 덕분에 계속 잘 쓰고 있습니다.

this.calendar.next(); 를 사용하여 크롬에서 캘린더 달을 이동시키고 있는데
일본의 한 pc에서만 달 이동이 잘 되지 않습니다.
어떤 부분을 어떻게 확인해야 할까요?

**Comment by dongsik-yoo** [comment]
@jungeun-cho Check this issue please.

**Comment by jungeun-cho** [comment]
@charmjeh 
Are you creating your own calendar instance without using the vue wrapper?

Here is an [example file](https://github.com/nhn/toast-ui.vue-calendar/blob/master/example/App.vue) using the vue wrapper.
Check it out.

```js
<calendar
  style="height: 800px"
  ref="tuiCal"
  ...
>
...
this.$refs.tuiCal.invoke('next'); // call method
```

**Comment by charmjeh** [comment]
질문을 잘 못 올려 tui.calendar에서 다시 질문 드렸습니다. 답변 주셔서 감사합니다. :)
