### ISSUE TITLE
Display semesters, cycles of years, seasons and combination. 

### ISSUE THREAD

**Issue by CyberPoison** [nhn/toast-ui.vue-calendar#59]
### Feature request

Hello everyone I'm using this template to my school project by the way the school use some abstracts times like weeks of semester and week/semester of cycles of year

My question is if there is a way to implement this kind of abstract date, like weeks of semester, semester of cycles of 3 years etc...

I'm based on the demo ui so as i can see there is a drop-down menu wish allow us to chose weekly, day, or month, 2/3 weeks etc.. But semesters or a cycle of year e.g 3 year, 
My school what schedule events for 3 years and some times for 2 weeks from X semester, and some other custom date. 

So there is a way to implement this kind of date showing in the ui?

Kind regards.

**Comment by adhrinae** [comment]
@CyberPoison 
I'm afraid to say there is no way to implement your idea with `tui-calendar`.
This calendar only offers kind of stereotype views.

If you are looking for a view rendering multiple months at the same time, try other projects like `fullcalendar`.

https://github.com/fullcalendar/fullcalendar/issues/470
